config/routes.rb
Rails.application.routes.draw do

  root 'store#index', as: 'store_index'

  constraints(-> (req) { req.env["HTTP_USER_AGENT"] !~ /Firefox/ }) do
    get 'admin' => 'admin#index'
    get 'my-orders', to: 'users#orders'
    get 'my-items', to: 'users#line_items'
    namespace :admin do
      get :index
      resources :reports
      resources :catagories do
        get :catagory_with_subcatagory, on: :collection
      end
    end
    resources :users do
      get :orders, on: :collection
      get :line_items, on: :collection
    end
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      get 'logout' => :destroy
    end
    resources :catagories do
      get 'books', to: 'store#index', constraints: { catagory_id: /[\D]+.*/ }
      get :products, to: 'products#index', path: :books
    end
    resources :support_requests, only: [ :index, :update ]
    resources :orders
    resources :line_items
    resources :carts
    resources :products, path: :books do
      get :who_bought, on: :member
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  ADMIN_EMAIL = 'admin@depot.com'

  validates :name, :email, presence: true, uniqueness: true
  validates :email, allow_blank: true, format: { 
    with: VALID_EMAIL_REGEX,
		message: 'is not an email' 
  }
  
  has_secure_password

  after_create_commit :notify_with_welcome_email
  before_update :ensure_user_is_not_admin_before_update
  before_destroy :ensure_user_is_not_admin_before_destroy
  after_destroy :ensure_an_admin_remains

  has_many :orders, dependent: :restrict_with_error
  has_many :line_items, through: :orders
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  has_many :counters, dependent: :destroy

  class Error < StandardError
  end

  def set_last_activity
    self.last_activity_time = Time.current
    self.save
  end

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last User"
    end
  end

  def ensure_user_is_not_admin_before_update
    if email.eql?(ADMIN_EMAIL)
      errors.add(:email, 'can\'t update admin')
      throw :abort 
    end
  end

  def ensure_user_is_not_admin_before_destroy
    if email.eql?(ADMIN_EMAIL)
      errors.add(:email, 'can\'t delete admin')
      throw :abort 
    end
  end
  
  def notify_with_welcome_email
    UserMailer.created(self).deliver_later
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, :set_last_activity, :set_counter, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_address
  end

  # GET /users/1/edit
  def edit
  end

  def line_items
    @items = @current_user.line_items.paginate(page: params[:page], per_page: ENTRY_PER_PAGE)
    # render layout: 'myorders'
  end

  def orders
    @orders = @current_user.orders.paginate(page: params[:page], per_page: ENTRY_PER_PAGE)
    # render layout: 'myorders'
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to store_index_path, notice: "User #{@user.name} was successfully created. You can login now" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if !@user.try(:authenticate, params[:user][:current_password])
        format.html { redirect_to edit_user_path(@user), notice: "User #{@user.name} current password not matched" }
      elsif @user.update(user_params)
        format.html { redirect_to store_index_path, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User #{@user.name} deleted." }
        format.json { head :no_content }
      end
    else
      redirect_to users_url, alert: @user.errors.full_messages.join
    end
  end

rescue_from 'User::Error' do |exception|
    redirect_to users_url, notice: exception.message
end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation,
      address_attributes: [ :state, :city, :country, :pincode ]
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<div class="depot_form">

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Enter User Details</h2>

  <div class="field">
    <%= form.label :name, 'Name:' %>
    <%= form.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :current_password, 'Current Password:' %>
    <%= form.password_field :current_password, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :password, 'Password:' %>
    <%= form.password_field :password, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, 'Confirm:' %>
    <%= form.password_field :password_confirmation,
      id: :user_password_confirmation,
      size: 40 %>
  </div>

  <%= form.fields_for :address do |address_form| %>
    <div>
      <%= address_form.label :state %>
      <%= address_form.text_field :state %>
    </div>

    <div>
      <%= address_form.label :city %>
      <%= address_form.text_field :city %>
    </div>

    <div>
      <%= address_form.label :country %>
      <%= address_form.text_field :country %>
    </div>

    <div>
      <%= address_form.label :pincode %>
      <%= address_form.text_field :pincode %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Enter User Details</h2>

  <div class="field">
    <%= form.label :name, 'Name:' %>
    <%= form.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :email, 'Email:' %>
    <%= form.text_field :email, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :role, 'Role:' %>
    <%= form.text_field :role%>
  </div>

  <div class="field">
    <%= form.label :password, 'Password:' %>
    <%= form.password_field :password, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, 'Confirm:' %>
    <%= form.password_field :password_confirmation,
      id: :user_password_confirmation,
      size: 40 %>
  </div>

  <%= form.fields_for :address do |address_form| %>
    <div>
      <%= address_form.label :state %>
      <%= address_form.text_field :state %>
    </div>

    <div>
      <%= address_form.label :city %>
      <%= address_form.text_field :city %>
    </div>

    <div>
      <%= address_form.label :country %>
      <%= address_form.text_field :country %>
    </div>

    <div>
      <%= address_form.label :pincode %>
      <%= address_form.text_field :pincode %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'edit_form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'flash' %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/line_items.html.erb
<% if @items.present? %>
  <h1>Your Orders</h1>
  <table border = 1>
    <tr>
      <th> Product Id </th>
      <th> Quantity </th>
    </tr>
    <% @items.includes(:product).each do |line_item| %>
      <tr>
        <td> <%= line_item.product.title %> </td>
        <td> <%= line_item.quantity %> </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h1> No Line Items present </h1>
<% end %>
<%= will_paginate @items %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/orders.html.erb
<% if @orders.present? %>
  <h1>Your Orders</h1>
  <table border = 1>
    <tr>
      <th> Items</th>
      <th> Total Price</th>
    </tr>
    <% @orders.includes(line_items: :product).each do |order| %>
      <tr>
        <td>
          <% total = 0 %>
          <% order.line_items.each do |line_item| %>
            <%= pluralize(line_item.quantity, line_item.product.title) %>
            <% total += line_item.total_price %>
          <% end %>
        </td>
        <td>
          <%= total %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h1> No Orders Present </h1>
<% end %>
<%= will_paginate @orders %>

app/views/users/show.html.erb
<%= render 'flash' %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
  <br>
  <strong>Email:</strong>
  <%= @user.email %>
  <br>
  <% address = @user.address %>
  <strong>City:</strong>
  <%= address.city %>
  <br>
  <strong>State:</strong>
  <%= address.state %>
  <br>
  <strong>Country:</strong>
  <%= address.country %>
  <br>
  <strong>PinCode:</strong>
  <%= address.pincode %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>